repository: karanpuri1406-sys/traction-website
branch: main

media:
  input: images
  output: images

collections:
  - name: hero
    label: Hero Section
    type: single
    file: content/hero.json
    fields:
      - name: title
        label: Main Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: text
        required: true
      - name: cta_text
        label: Button Text
        type: string
        required: true

  - name: blog
    label: Blog Posts
    type: collection
    path: content/blog
    format: md
    fields:
      - name: title
        label: Post Title
        type: string
        required: true
      - name: date
        label: Publication Date
        type: datetime
        required: true
      - name: author
        label: Author Name
        type: string
        required: true
      - name: excerpt
        label: Excerpt
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text
        required: true
